version: "3"

services: 

  postgres:
    image: postgres:10.0-alpine
    container_name: mybooks-postgres
    volumes: 
      - /home/rpg/Docker/mybooks-postgres:/var/lib/postgresql/data
    restart: always
    networks: 
      - books

  nginx:
    image: nginx
    container_name: mybooks-nginx
    ports:
      - "8181:80"
    volumes:
      - /home/rpg/Docker/nginx/html/imageBook:/usr/share/nginx/html
    restart: always
    networks:
      - books
       
  app:
    build: .
    container_name: mybooks
    ports:
      - "3333:3333"
    volumes: 
      - .:/usr/app
      - /home/rpg/Docker/nginx/html/imageBook:/usr/app/public/images
    command: yarn prod
    restart: always
    networks: 
      - books
                   
networks:
  books:
    driver: bridge
    