version: "3"

services:
  postgres:
    image: postgres:10.0-alpine
    container_name: books-db
    volumes:
      - /home/rpg/docker/books-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - books

  app:
    build: .
    container_name: books-api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - /home/rpg/docker/nginx/books:/usr/app/public/images
    command: yarn prod
    restart: always
    networks:
      - books

networks:
  books:
    driver: bridge
